# path to root directory
root_dir: ${oc.env:PROJECT_ROOT} 

# path to data directory
data_dir: ${paths.root_dir}/data

# path to output directory
output_dir: ${paths.root_dir}/output

# path to working directory
work_dir: ${hydra:runtime.cwd}